name: Build and push Docker image with tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: false
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./
          push: true
          tags: bouvetasa/image-sftp:${{ github.event.inputs.tag }}